title: Music 580 - Immersive Audio
description: none
theme: just-the-docs

url: https://byu-elecmusicstudio.github.io/ImmersiveMusicComp/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

logo: "/assets/images/byu-logo.svg"

source: "/docs"



collections:
  articles:
    permalink: "/:collection/:path/"
    output: true
  media:
    permalink: "/:collection/:path/"
    output: true
  tools:
    permalink: "/:collection/:path/"
    output: true
    
just_the_docs:
  collections:
    articles:
      name: Articles
    media:
      name: Media
    tools:
      name: Tools

