title: Immersive Music Composition
description: none
theme: just-the-docs

url: https://byu-elecmusicstudio.github.io/ImmersiveMusicComp/

#aux_links:
  #Template Repository: https://github.com/just-the-docs/just-the-docs-template

logo: "/assets/images/byu-logo.svg"
