title: Music 580 - Immersive Audio
description: none
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

logo: "/assets/images/byu-logo.svg"

source: "/docs"

collections:
  articles:
    output: true
  media:
    output: true
  tools:
    output: true
